const stage=document.querySelector('#stage'),base='../';
const names=['카엘','세라','시온','로엔','레온','벨라','유안','아이리스','에녹','엘리아','루카','리네','아드리안','스텔라','로빈','티아','바론','클레어','요한','하젤','빅터','로렌','테오','미리엄','렌','다나','미엘','실비아','카일','제나','니코','리코'];
const types=['INTJ','INTP','ENTJ','ENTP','INFJ','INFP','ENFJ','ENFP','ISTJ','ISFJ','ESTJ','ESFJ','ISTP','ISFP','ESTP','ESFP'];
let selected=0,filter='all',page=0;
const ch=i=>lumiaAssetPath(base+`01_characters/01_images/CH${String(i+1).padStart(2,'0')}_${names[i]}.png`);
const img=(src,cls='',alt='')=>`<img src="${lumiaAssetPath(base+src)}" class="${cls}" alt="${alt}">`;
const corners=()=>['tl','tr','br','bl'].map(p=>img('04_ui/00_images/02_UI02_프레임_모서리.png','corner '+p)).join('');
const bg=n=>img(`03_backgrounds/01_exports/${n}_1920x1080.png`,'backdrop');
// Fixed review canvas: preserve 1920×1080 during tiled browser capture.
function modal(title,body){const el=document.createElement('div');el.className='popup';el.innerHTML=`<article class="paper">${corners()}<h2>${title}</h2><p>${body}</p><button class="secondary">닫기</button></article>`;stage.append(el);el.querySelector('button').onclick=()=>el.remove();el.querySelector('button').focus()}
function showTitle(){location.hash='title';stage.innerHTML=bg('BG01_아르카디아_입구와_호수')+`<div class="veil"></div><div class="top-note">아르카디아 룬 아카데미</div><div class="utilities"><button aria-label="도움말" id="help">?</button><button aria-label="설정" id="settings">⚙</button></div><section class="title-box paper">${corners()}<div class="crest">❧</div><span class="eyebrow">LUMIA CHRONICLES</span><h1>루미아 전기</h1><h2>마음을 품은 룬</h2><p>낯선 친구, 작은 선택.<br>너의 마음에서 시작되는 새로운 이야기.</p><button class="primary" id="start">✧ &nbsp; 새로운 이야기 시작</button><button class="secondary" disabled>이어하기 · 저장된 이야기 없음</button></section><div class="footer">호수 너머, 너를 기다리는 이야기가 있어.</div>`;document.querySelector('#start').onclick=showSelect;document.querySelector('#help').onclick=()=>modal('너의 이야기를 시작해요','함께할 캐릭터를 고르고 아르카디아를 둘러보세요. 시안에서는 온실의 첫 조사 장면을 살펴볼 수 있어요.');document.querySelector('#settings').onclick=()=>modal('화면 안내','이 화면은 디자인 검토용 시안입니다. 소리와 저장 설정은 아직 연결되지 않았어요.')}
function showSelect(){location.hash='select';let list=names.map((_,i)=>i).filter(i=>filter==='all'||i%2===(filter==='male'?0:1)),max=Math.ceil(list.length/6);page=Math.min(page,max-1);stage.innerHTML=bg('BG01_아르카디아_입구와_호수')+`<div class="select-brand">❧ &nbsp; 루미아 전기: 마음을 품은 룬</div><section class="select-panel paper">${corners()}<aside class="filters"><div class="step"><b>1</b> 친구 찾기</div>${[['all','모두 보기'],['male','남자 캐릭터'],['female','여자 캐릭터']].map(([v,t])=>`<button class="filter ${filter===v?'on':''}" data-filter="${v}" aria-pressed="${filter===v}">${t}</button>`).join('')}<div class="step" style="margin-top:90px"><b>2</b> 캐릭터 선택</div><p class="subtext">32개의 서로 다른 마음.<br>너의 이야기를 함께할<br>친구를 골라 주세요.</p><button class="secondary" id="home" style="margin-top:40px">‹ 이전</button></aside><section class="catalog"><h2>어떤 친구로 모험을 시작할까요?</h2><div class="cards">${list.slice(page*6,page*6+6).map(i=>`<button class="card ${selected===i?'selected':''}" data-char="${i}" aria-label="${names[i]} 선택" aria-pressed="${selected===i}"><img src="${ch(i)}" alt="${names[i]} 전신">${selected===i?'<span class="check">✓</span>':''}<span class="name">${names[i]}</span></button>`).join('')}</div><div class="pages"><button id="prev" aria-label="이전 페이지" ${page===0?'disabled':''}>‹</button><span>${page+1} / ${max} &nbsp; · &nbsp; ${list.length}명</span><button id="next" aria-label="다음 페이지" ${page===max-1?'disabled':''}>›</button></div></section><aside class="preview"><img class="hero" src="${ch(selected)}" alt="선택한 ${names[selected]} 전신"><div class="profile"><h2>${names[selected]}</h2><p>아르카디아의 학생</p><span class="chip">${types[Math.floor(selected/2)]}</span><span class="chip">${selected%2?'여자':'남자'} 캐릭터</span></div><button class="primary" id="enter">✧ &nbsp; 이 캐릭터로 시작하기</button></aside></section>`;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;page=0;showSelect()});document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{selected=+b.dataset.char;showSelect()});document.querySelector('#prev').onclick=()=>{page--;showSelect()};document.querySelector('#next').onclick=()=>{page++;showSelect()};document.querySelector('#home').onclick=showTitle;document.querySelector('#enter').onclick=()=>selected===0?showAdventure():modal('캐릭터 선택 확인',`${names[selected]}의 전신 시안을 선택했어요. 온실 조립 시안은 준비된 카엘 SD 원화로 확인할 수 있어요. 캐릭터 목록에서 카엘을 선택해 주세요.`)}
function showAdventure(){location.hash='adventure';stage.innerHTML=bg('BG07_유리_온실')+`<div class="location">유리 온실 &nbsp; · &nbsp; 오후</div><section class="objective paper"><small>첫 번째 이야기</small><h2>빛을 잃은 온실</h2><p>◇ 시든 식물을 살펴보기</p></section><div class="tools">${[['UI08_가방','가방'],['UI09_발견기록','발견 기록'],['UI10_힌트','힌트']].map(([f,t],i)=>`<button class="tool" data-tool="${i}">${img('04_ui/00_images/'+f+'.svg')} ${t}${i===1?'<i class="dot"></i>':''}</button>`).join('')}</div><div class="stack" aria-label="달빛 약초 1개">${img('07_adventure_objects/00_images/04_OBJ03_달빛_약초.png')}<b>1</b></div>${img('08_sd_character/00_images/00_SD03_frames/14_SD03_S_01.png','actor','카엘 SD')}${img('07_adventure_objects/00_images/01_OBJ01_조사_식물_시듦.png','prop','시든 식물')}<button class="interact" id="inspect"><b>E</b> 시든 식물 &nbsp; ◇</button>${img('06_adventure_environment/00_images/14_ENV12_전경_식물_A.png','foreground left-leaf')}${img('06_adventure_environment/00_images/15_ENV13_전경_식물_B.png','foreground right-leaf')}<div class="hintline">주변을 관찰하고, 마음이 가는 행동을 골라 보세요.</div><section class="dialogue paper">${corners()}<img class="portrait" src="${ch(0)}" alt="카엘"><div class="speaker">카엘</div><p id="line">흙은 젖어 있는데 잎은 시들었네.<br>물을 더 주기 전에, 원인을 먼저 알아봐야겠어.</p><div class="choices"><button class="primary" id="look">잎을 자세히 살펴본다</button><button class="secondary" id="around">주변을 더 둘러본다</button></div></section><button class="back" id="back">‹ 캐릭터 선택</button>`;document.querySelector('#back').onclick=showSelect;const inspect=()=>{document.querySelector('#line').innerHTML='잎맥에 희미한 룬 자국이 있어.<br>이 모양을 기록해 두면 단서를 찾는 데 도움이 되겠지.'};document.querySelector('#inspect').onclick=inspect;document.querySelector('#look').onclick=inspect;document.querySelector('#around').onclick=()=>{document.querySelector('#line').innerHTML='다른 식물들은 괜찮아 보여.<br>이 화분 주변에만 달라진 것이 있는지 살펴보자.'};document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{let i=+b.dataset.tool;modal(['가방','발견 기록','작은 힌트'][i],[img('07_adventure_objects/00_images/04_OBJ03_달빛_약초.png','','달빛 약초')+'<br>달빛 약초 × 1','유리 온실<br>• 젖은 흙과 시든 잎<br>• 잎맥에 남아 있는 룬 자국','물을 더 주기 전에 잎과 화분 주변을 관찰해 보세요.'][i])})}
if(location.hash==='#adventure')showAdventure();else if(location.hash==='#select')showSelect();else showTitle();
