export function startAdventure(container,content,state,callbacks){
 const Phaser=window.Phaser;if(!Phaser)throw new Error('게임 엔진 파일을 읽지 못했어요.');
 const map=content.map;let sceneRef=null,blocked=false,target=null,lastSave=0;
 class Greenhouse extends Phaser.Scene{
  constructor(){super('Greenhouse');}
  preload(){for(const [key,url] of Object.entries(content.assets))this.load.image(key,url);for(const d of content.sd.directions)this.load.spritesheet('sd-'+d,content.sd.prefix+d+content.sd.suffix,{frameWidth:content.sd.frameWidth,frameHeight:content.sd.frameHeight});this.load.on('loaderror',f=>callbacks.error('이미지를 읽지 못했어요: '+f.key));}
  create(){sceneRef=this;this.game.canvas.tabIndex=0;this.game.canvas.setAttribute('aria-label','온실 탐험 화면. WASD 또는 방향키 이동, E 상호작용');this.game.canvas.focus();this.physics.world.setBounds(48,48,map.width-96,map.height-96);this.cameras.main.setBounds(0,0,map.width,map.height);this.add.tileSprite(0,0,map.width,map.height,'floor').setOrigin(0).setTint(0xb8c5a5);const walls=this.add.graphics();walls.fillStyle(0x294c3b,.95);walls.fillRect(0,0,map.width,45);walls.fillRect(0,0,45,map.height);walls.fillRect(map.width-45,0,45,map.height);walls.lineStyle(5,0x81976b,.65);for(let x=0;x<map.width;x+=180)walls.strokeRect(x,6,170,38);
   const decor=(o,key=o.asset)=>{const image=this.add.image(o.x,o.y,key).setOrigin(.5,o.originY??.9);image.setDisplaySize(o.width,image.height*o.width/image.width);image.setDepth(o.y);return image;};map.decorations.forEach(o=>decor(o));
   this.objects=new Map();map.objects.forEach(o=>{if(o.asset)this.objects.set(o.id,decor(o,o.id==='plant'&&state.restored?'recovered':o.id==='rune'&&state.restored?'runeOn':o.asset));else{this.add.rectangle(o.x,o.y,140,70,0x476e53,.8).setStrokeStyle(2,0xb5c197);this.add.text(o.x,o.y,'温室 / 입구',{fontFamily:'Malgun Gothic',fontSize:'17px',color:'#e9e8cf'}).setOrigin(.5).setDepth(o.y+5);}});
   this.player=this.physics.add.sprite(state.position.x,state.position.y,'sd-S',1).setOrigin(.5,content.sd.footY/content.sd.frameHeight).setDisplaySize(content.sd.displayWidth,content.sd.displayWidth).setDepth(state.position.y);this.player.body.setSize(64,30).setOffset(96,195);this.player.setCollideWorldBounds(true);
   const obstacles=this.physics.add.staticGroup();for(const r of map.collisions){const box=this.add.rectangle(r.x+r.width/2,r.y+r.height/2,r.width,r.height,0x000000,0);obstacles.add(box);box.body.setSize(r.width,r.height);}this.physics.add.collider(this.player,obstacles);
   for(const d of content.sd.directions)this.anims.create({key:'walk-'+d,frames:this.anims.generateFrameNumbers('sd-'+d,{frames:[0,1,2,1]}),frameRate:content.sd.fps,repeat:-1});
   this.cameras.main.startFollow(this.player,true,.1,.1);this.cameras.main.setDeadzone(140,90);this.keys=this.input.keyboard.addKeys('W,A,S,D,UP,DOWN,LEFT,RIGHT,E');this.input.keyboard.addCapture(['W','A','S','D','UP','DOWN','LEFT','RIGHT','E']);this.input.keyboard.on('keydown-E',event=>{if(!blocked&&!event.repeat&&target)callbacks.interact(target.id);});this.input.on('pointerdown',p=>{if(!blocked)this.destination={x:p.worldX,y:p.worldY};});this.marker=this.add.text(0,0,'◇',{fontSize:'30px',color:'#e8d798'}).setOrigin(.5).setDepth(3000);this.direction='S';this.refreshWorld();
  }
  refreshWorld(){const herb=this.objects.get('herb');herb?.setVisible(!state.herbs);if(state.restored){this.objects.get('plant')?.setTexture('recovered');this.objects.get('rune')?.setTexture('runeOn');if(!this.glow)this.glow=this.add.image(1400,330,'glow').setDisplaySize(220,220).setAlpha(.55).setDepth(389);}target=null;callbacks.target(null);}
  targetInfo(o){return o?{...o,label:state.restored&&o.id==='plant'?'회복된 유리꽃':state.restored&&o.id==='rune'?'빛이 흐르는 룬':o.label}:null;}
  update(time){if(!this.player)return;if(blocked){this.destination=null;this.player.setVelocity(0);this.player.anims.stop();return;}const k=this.keys;let dx=Number(k.D.isDown||k.RIGHT.isDown)-Number(k.A.isDown||k.LEFT.isDown),dy=Number(k.S.isDown||k.DOWN.isDown)-Number(k.W.isDown||k.UP.isDown);if(dx||dy)this.destination=null;else if(this.destination){dx=this.destination.x-this.player.x;dy=this.destination.y-this.player.y;if(Math.hypot(dx,dy)<8){dx=dy=0;this.destination=null;}}const len=Math.hypot(dx,dy)||1;this.player.setVelocity(dx/len*map.speed,dy/len*map.speed);if(dx||dy){this.direction=dy>0?(dx<0?'SW':dx>0?'SE':'S'):dy<0?(dx<0?'NW':dx>0?'NE':'N'):dx>0?'E':'W';this.player.play('walk-'+this.direction,true);}else{this.player.anims.stop();this.player.setTexture('sd-'+this.direction,1);}this.player.setDepth(this.player.y);state.position={x:this.player.x,y:this.player.y};if(time-lastSave>1500){callbacks.save();lastSave=time;}
   let next=null,dist=map.interactionRadius;for(const o of map.objects){if(o.id==='herb'&&state.herbs)continue;const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,o.x,o.y);if(d<dist){dist=d;next=o;}}this.marker.setVisible(!!next);if(next)this.marker.setPosition(next.x,next.y-110);if(next?.id!==target?.id){target=next;callbacks.target(this.targetInfo(next));}
  }
 }
 const game=new Phaser.Game({type:Phaser.AUTO,parent:container,width:1100,height:700,backgroundColor:'#263c2e',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},physics:{default:'arcade',arcade:{debug:false}},scene:Greenhouse,render:{antialias:true}});
 return {destroy(){callbacks.save();game.destroy(true);},pause(value){blocked=value;if(sceneRef?.input.keyboard){sceneRef.input.keyboard.resetKeys();sceneRef.input.keyboard.enabled=!value;}},refresh(){sceneRef?.refreshWorld();},interact(){if(target)callbacks.interact(target.id);}};
}
