import {joystickVector,viewportSize} from './pointer-controls.mjs';
export function startAdventure(container,content,state,callbacks){
 const Phaser=window.Phaser;if(!Phaser)throw new Error('게임 엔진 파일을 읽지 못했어요.');
 const map=content.map;let sceneRef=null,blocked=false,target=null,lastSave=0,touch={x:0,y:0},touchId=null;
 const parent=document.getElementById(container),stick=document.querySelector('.touch-joystick'),knob=stick?.querySelector('.joystick-knob');
 const resetTouch=()=>{touch={x:0,y:0};touchId=null;if(knob)knob.style.transform='';};
 const moveTouch=e=>{if(e.pointerId!==touchId||blocked)return;const r=stick.getBoundingClientRect();touch=joystickVector(e.clientX-r.left-r.width/2,e.clientY-r.top-r.height/2,48);knob.style.transform=`translate(${touch.x*35}px,${touch.y*35}px)`;};
 stick?.addEventListener('pointerdown',e=>{if(blocked||touchId!==null)return;e.preventDefault();touchId=e.pointerId;stick.setPointerCapture(e.pointerId);moveTouch(e);});
 stick?.addEventListener('pointermove',moveTouch);for(const type of ['pointerup','pointercancel','lostpointercapture'])stick?.addEventListener(type,e=>{if(e.pointerId===touchId)resetTouch();});
 class Greenhouse extends Phaser.Scene{
  constructor(){super('Greenhouse');}
  preload(){for(const key of ['world','wilted','recovered','herb','glow'])this.load.image(key,content.assets[key]);for(const d of content.sd.directions)this.load.spritesheet('sd-'+d,content.sd.prefix+d+content.sd.suffix,{frameWidth:content.sd.frameWidth,frameHeight:content.sd.frameHeight});this.load.on('loaderror',f=>callbacks.error('이미지를 읽지 못했어요: '+f.key));}
  create(){sceneRef=this;this.game.canvas.tabIndex=0;this.game.canvas.setAttribute('aria-label','온실 탐험 화면. WASD 또는 방향키 이동, E 상호작용');this.game.canvas.focus();this.physics.world.setBounds(48,48,map.width-96,map.height-96);this.cameras.main.setBounds(0,0,map.width,map.height);this.add.image(0,0,'world').setOrigin(0).setDisplaySize(map.width,map.height).setDepth(-100);
   const decor=(o,key=o.asset)=>{const image=this.add.image(o.x,o.y,key).setOrigin(.5,o.originY??.9);image.setDisplaySize(o.width,image.height*o.width/image.width);image.setDepth(o.y);return image;};map.decorations.forEach(o=>decor(o));
   this.objects=new Map();map.objects.forEach(o=>{if(o.asset)this.objects.set(o.id,decor(o,o.id==='plant'&&state.restored?'recovered':o.asset));});
   this.restoreOverlay=this.add.graphics().setDepth(-90);
   this.player=this.physics.add.sprite(state.position.x,state.position.y,'sd-S',1).setOrigin(.5,content.sd.footY/content.sd.frameHeight).setDisplaySize(content.sd.displayWidth,content.sd.displayWidth).setDepth(state.position.y);this.player.body.setSize(64,30).setOffset(96,195);this.player.setCollideWorldBounds(true);
   const obstacles=this.physics.add.staticGroup();for(const r of map.collisions){const box=this.add.rectangle(r.x+r.width/2,r.y+r.height/2,r.width,r.height,0x000000,0);obstacles.add(box);box.body.setSize(r.width,r.height);}this.physics.add.collider(this.player,obstacles);
   for(const d of content.sd.directions)this.anims.create({key:'walk-'+d,frames:this.anims.generateFrameNumbers('sd-'+d,{frames:[0,1,2,1]}),frameRate:content.sd.fps,repeat:-1});
   this.cameras.main.startFollow(this.player,true,.1,.1);this.cameras.main.setDeadzone(Math.min(140,this.scale.width*.2),Math.min(90,this.scale.height*.15));this.keys=this.input.keyboard.addKeys('W,A,S,D,UP,DOWN,LEFT,RIGHT,E');this.input.keyboard.addCapture(['W','A','S','D','UP','DOWN','LEFT','RIGHT','E']);this.input.keyboard.on('keydown-E',event=>{if(!blocked&&!event.repeat&&target)callbacks.interact(target.id);});this.input.on('pointerdown',p=>{if(!blocked)this.destination={x:p.worldX,y:p.worldY};});this.marker=this.add.text(0,0,'◇',{fontSize:'30px',color:'#e8d798'}).setOrigin(.5).setDepth(3000);this.direction='S';this.refreshWorld();
  }
  refreshWorld(){this.objects.get('herb')?.setVisible(!state.herbs);this.objects.get('plant')?.setTexture(state.restored?'recovered':'wilted');this.restoreOverlay.clear();if(state.restored){this.restoreOverlay.fillStyle(0xffeab0,.13);this.restoreOverlay.fillRect(0,0,map.width,map.height);if(!this.glow)this.glow=this.add.image(900,190,'glow').setDisplaySize(210,210).setAlpha(.65).setDepth(220);}target=null;callbacks.target(null);}
  targetInfo(o){return o?{...o,label:state.restored&&o.id==='plant'?'회복된 유리꽃':state.restored&&o.id==='rune'?'빛이 흐르는 룬':o.label}:null;}
  update(time){if(!this.player)return;if(blocked){this.destination=null;this.player.setVelocity(0);this.player.anims.stop();return;}const k=this.keys;let dx=Number(k.D.isDown||k.RIGHT.isDown)-Number(k.A.isDown||k.LEFT.isDown)+touch.x,dy=Number(k.S.isDown||k.DOWN.isDown)-Number(k.W.isDown||k.UP.isDown)+touch.y;if(dx||dy)this.destination=null;else if(this.destination){dx=this.destination.x-this.player.x;dy=this.destination.y-this.player.y;if(Math.hypot(dx,dy)<8){dx=dy=0;this.destination=null;}}const len=Math.hypot(dx,dy)||1;this.player.setVelocity(dx/len*map.speed,dy/len*map.speed);if(dx||dy){this.direction=dy>0?(dx<0?'SW':dx>0?'SE':'S'):dy<0?(dx<0?'NW':dx>0?'NE':'N'):dx>0?'E':'W';this.player.play('walk-'+this.direction,true);}else{this.player.anims.stop();this.player.setTexture('sd-'+this.direction,1);}this.player.setDepth(this.player.y);state.position={x:this.player.x,y:this.player.y};if(time-lastSave>1500){callbacks.save();lastSave=time;}
   let next=null,dist=map.interactionRadius;for(const o of map.objects){if(o.id==='herb'&&state.herbs)continue;const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,o.x,o.y);if(d<dist){dist=d;next=o;}}this.marker.setVisible(!!next);if(next)this.marker.setPosition(next.x,next.y-110);if(next?.id!==target?.id){target=next;callbacks.target(this.targetInfo(next));}
  }
 }
 const size=viewportSize(parent.clientWidth,parent.clientHeight);
 const game=new Phaser.Game({type:Phaser.AUTO,parent:container,width:size.width,height:size.height,resolution:1,fps:{target:30,forceSetTimeOut:false},backgroundColor:'#263c2e',scale:{mode:Phaser.Scale.NONE,autoCenter:Phaser.Scale.NO_CENTER},physics:{default:'arcade',arcade:{debug:false}},scene:Greenhouse,render:{antialias:true,powerPreference:'low-power'}});
 const observer=new ResizeObserver(()=>{const next=viewportSize(parent.clientWidth,parent.clientHeight);game.scale.resize(next.width,next.height);sceneRef?.cameras.main.setViewport(0,0,next.width,next.height);});observer.observe(parent);
 return {destroy(){observer.disconnect();resetTouch();game.destroy(true);},updateState(next){state=next;},pause(value){blocked=value;if(value)resetTouch();if(sceneRef?.input.keyboard){sceneRef.input.keyboard.resetKeys();sceneRef.input.keyboard.enabled=!value;}},refresh(){sceneRef?.refreshWorld();},worldChange(){if(sceneRef){sceneRef.cameras.main.flash(700,255,235,170);const flower=sceneRef.objects.get('plant');if(flower)sceneRef.tweens.add({targets:flower,alpha:{from:.3,to:1},duration:1400});}},interact(){if(!blocked&&target)callbacks.interact(target.id);}};
}
