import {freshState,inspectPlant,collectHerb,recoverWorld,makeReport} from './state.mjs';
import {loadSave,saveState} from './storage.mjs';
import {connected,rotate,reachable} from './puzzle.mjs';
import {startAdventure} from './adventure.mjs';
const app=document.querySelector('#app'),modalRoot=document.querySelector('#modal-root');
let content,state=freshState(),game=null,saved=loadSave(),toastTimer,modalInvoker;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=(id,cls='')=>`<img class="${cls}" src="${esc(content.assets[id])}" alt="${esc(id==='sion'?'시온':id==='bern'?'베른':id==='kael'?'카엘':'')}" data-asset="${id}">`;
const button=(text,action,cls='primary',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${esc(text)}</button>`;
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4000);}
function persist(){if(state.scene==='title')return;const ok=saveState(state);const el=document.querySelector('.saved');if(el)el.textContent=ok?'이 브라우저에 기록됨':'저장하지 못함';if(!ok&&!persist.warned){persist.warned=true;toast('브라우저에 기록을 저장하지 못했어요. 이번 플레이는 계속할 수 있어요.');}if(ok)saved={state:structuredClone(state),error:null};}
function transition(scene){if(game){game.destroy();game=null;}closeModal();state.scene=scene;state.node=0;persist();render();}
function shell(bg,body,label='',cls=''){return `<main class="screen ${cls}" style="background-image:url('${esc(content.assets[bg])}')"><header class="topbar"><div class="brand">LUMIA</div><div class="topright"><span class="caption">${esc(label)}</span><span class="saved">${state.scene==='title'?'PC Prototype':'이 브라우저에 기록됨'}</span>${state.scene==='title'?'':button('메뉴','menu','ghost')}</div></header>${body}</main>`;}
function render(){
 switch(state.scene){
 case 'title':app.innerHTML=shell('entrance',`<section class="title-content"><div class="title-kicker">ARCADIA RUNE ACADEMY</div><h1>${esc(content.title)}</h1><p>빛이 멈춘 온실, 그리고 말하지 못한 작은 실수.<br>당신의 관찰과 선택으로 오늘의 이야기를 이어가세요.</p><div class="title-actions">${button('새 이야기 시작','new')}${button('이어하기','continue','ghost',saved.state?'':'disabled')}</div>${saved.error?`<p class="restore-banner">${esc(saved.error)}</p>`:''}</section><div class="footer-note">임시 대본 · 카엘 1명 · 로컬 기록</div>`);break;
 case 'select':app.innerHTML=shell('entrance',`<div class="select-layout"><div class="portrait-stage">${img('kael')}</div><section class="character-copy"><div class="eyebrow">YOUR STORY BEGINS</div><h1>${esc(content.character.name)}</h1><p>${esc(content.character.title)}</p><div class="chips"><span class="chip">${content.character.age}세</span><span class="chip">이번 이야기의 주인공</span></div><p>${esc(content.character.description)}</p><div class="quote">“${esc(content.character.quote)}”</div>${button('카엘로 시작하기','admit')}<p class="caption">대표 캐릭터 1명으로 탐험 경험을 확인합니다.</p></section></div>`,'캐릭터 선택');break;
 case 'admission':app.innerHTML=shell('entrance',`<div class="admission"><section class="invitation"><div class="eyebrow">ARCADIA · INVITATION</div><h2>카엘에게</h2><p>아르카디아 고서원에 온 것을 환영합니다.<br>이곳의 룬은 마음과 의지에 귀 기울입니다.<br>당신만의 시선으로, 오늘의 이야기를 만나 보세요.</p>${button('아르카디아에 도착하기','arrive')}</section></div>`,'입학 초대장');break;
 case 'plaza':case 'greenhouse':case 'reaction':case 'room':renderDialogue();break;
 case 'choice':renderChoice();break;
 case 'adventure':renderAdventure();break;
 case 'record':renderRecord();break;
 case 'report':renderReport();break;
 }
 app.querySelectorAll('img').forEach(el=>el.addEventListener('error',()=>{el.classList.add('missing-asset');el.alt='이미지 준비 중';},{once:true}));
}
function renderDialogue(){const name={plaza:'시계탑 광장',greenhouse:'유리 온실',reaction:'빛이 돌아온 온실',room:'My Room'}[state.scene],bg=state.scene==='reaction'?'greenhouse':state.scene;const lines=content.dialogue[state.scene],node=lines[Math.min(state.node,lines.length-1)];const final=state.node===lines.length-1;const label=final?{plaza:'온실로 가기',greenhouse:'온실 탐험하기',reaction:'시온에게 답하기',room:'오늘 돌아보기'}[state.scene]:'이야기 듣기';app.innerHTML=shell(bg,`<div class="scene-title"><div class="eyebrow">${state.scene==='room'?'A QUIET MOMENT':'ARCADIA LIFE'}</div><h2>${name}</h2><p>${state.restored&&state.scene==='reaction'?'잎 사이로 따뜻한 빛이 다시 흐른다.':'마음의 이야기가 머무는 곳'}</p></div>${img(node.portrait,'life-portrait')}<section class="life-dialogue" aria-live="polite"><div class="speaker">${esc(node.speaker)}</div><p class="dialogue-text">${esc(node.text)}</p><div class="dialogue-actions">${state.scene==='greenhouse'?button('시온에게 말 걸기','question',''):''}${button(label,'next')}</div></section>`,name);}
function renderChoice(){app.innerHTML=shell('greenhouse',`<div class="scene-title"><div class="eyebrow">A MOMENT OF CHOICE</div><h2>시온에게 어떤 말을 건넬까?</h2></div>${img('sion','life-portrait')}<section class="life-dialogue"><div class="speaker">카엘의 선택</div><p>각기 다른 방법으로 시온의 다음 걸음을 함께할 수 있어요.</p><div class="choice-list">${content.choices.map(c=>button(c.label,'choose','',`data-id="${c.id}"`)).join('')}</div></section>`,'온실 · 이야기 선택');}
function renderAdventure(){app.innerHTML=shell('greenhouse',`<div class="game-wrap" id="game"></div><aside class="objective"><small>유리 온실 · ADVENTURE</small><p id="objective">${esc(objective())}</p></aside><nav class="tools" aria-label="탐험 도구">${['bag','journal','hint'].map((id,i)=>`<button class="tool" data-action="${id}">${img(id)}<span>${['가방','발견 기록','힌트'][i]}</span></button>`).join('')}</nav><div class="controls">WASD / 방향키 이동 · E 상호작용</div><button class="interact" data-action="interact" hidden>상호작용</button>`,'온실 탐험','adventure-screen');try{game=startAdventure('game',content,state,{save:persist,error:toast,target:o=>{const b=app.querySelector('.interact');if(!b)return;b.hidden=!o;if(o)b.textContent=`${o.label} · ${o.action} [E]`;},interact});}catch(e){toast(e.message);app.querySelector('#game').innerHTML=`<div class="paper-panel"><h2>온실을 불러오지 못했어요</h2><p>${esc(e.message)}</p>${button('Life로 돌아가기','return-life')}</div>`;}}
function objective(){return content.objectives[state.restored?'restored':state.runeObserved?'observed':'explore'];}
function refreshAdventure(){persist();game?.refresh();const el=document.querySelector('#objective');if(el)el.textContent=objective();}
function interact(id){if(modalRoot.children.length)return;if(id==='plant'){inspectPlant(state);refreshAdventure();openModal(content.knowledge.title,`<p>${esc(state.restored?'유리꽃이 다시 고개를 든다. 연결된 룬의 빛이 잎 사이로 흐른다.':content.knowledge.text)}</p><p class="question-label">발견 기록에 남긴 사실 · Knowledge</p>`);}else if(id==='herb'){collectHerb(state);refreshAdventure();openModal('달빛 약초를 발견했어요',`<div class="item-card">${img('herb')}<div><h3>${esc(content.herb.name)} × 1</h3><p>${esc(content.herb.text)}</p></div></div><p class="question-label">가방에 보관한 물건 · Item</p>`);}else if(id==='rune'){if(state.restored){openModal('빛이 흐르는 룬','<p>빛의 길은 이어져 있다. 시온에게 돌아가 이야기를 나누자.</p>');return;}state.runeObserved=true;refreshAdventure();openModal('룬의 흔적',`<p>${esc(content.runeObservation)}</p><div class="modal-actions">${button('빛의 길 연결하기','puzzle')}</div>`);}else if(id==='exit'){if(!state.restored){openModal('잠시 온실을 나갈까요?',`<p>찾은 사실과 물건, 룬의 배열은 이 브라우저에 남아요. 다시 돌아와 탐험을 이어갈 수 있어요.</p><div class="modal-actions">${button('Life로 돌아가기','return-life')}</div>`);}else transition('reaction');}}
function renderRecord(){const choice=content.choices.find(c=>c.id===state.choice),reflection=content.reflections.find(c=>c.id===state.reflection);app.innerHTML=shell('room',`<div class="center-panel"><section class="paper-panel"><div class="eyebrow">HEART RECORD · 나만의 기록</div><h2>${esc(content.title)}</h2><div class="memory-art" style="background-image:url('${content.assets.greenhouse}')"></div><p>빛의 흐름을 되찾고, 시온이 숨겨 두었던 이야기를 들었다.</p><p class="record-meta">나의 선택<br>${esc(choice?.label)}</p><p class="record-meta">내 마음에 남은 장면<br>${esc(reflection?.label)}</p><p class="private-note">이 성찰은 개인 기록이며 부모 리포트에 포함되지 않아요.</p>${button('부모 리포트 미리보기','report')}</section></div>`,'오늘의 추억');}
function renderReport(){const report=makeReport(state),choice=content.choices.find(c=>c.id===report.choice);const sections=[['어떤 이야기였나요?',content.report.context],['어떻게 했나요?',choice?.description??'아직 주요 선택 기록이 없어요.'],['그 뒤에는 어떻게 되었나요?',content.report.result],['함께 이야기해 보세요',content.report.prompt]];app.innerHTML=shell('plaza',`<div class="center-panel"><section class="paper-panel"><div class="eyebrow">STORY LETTER · 부모 리포트 미리보기</div><h2>오늘, 온실에 빛이 돌아왔어요</h2><div class="report-grid">${sections.map(([h,p])=>`<section class="report-item"><h3>${h}</h3><p>${esc(p)}</p></section>`).join('')}</div><p class="private-note">같은 브라우저에서 확인하는 임시 리포트입니다. 개인 성찰과 일반 NPC 대화 답변은 포함하지 않습니다.</p><div class="dialogue-actions">${button('나의 기록 보기','record','')}${button('타이틀로 돌아가기','title')}</div></section></div>`,'이야기의 끝');}
function openModal(title,body,extraClass=''){modalInvoker=document.activeElement;game?.pause(true);modalRoot.innerHTML=`<div class="modal-backdrop"><dialog open class="modal ${extraClass}" aria-labelledby="modal-title"><button class="modal-close" data-action="close" aria-label="닫기">×</button><h2 id="modal-title">${esc(title)}</h2>${body}</dialog></div>`;modalRoot.querySelector('button')?.focus();}
function closeModal(){if(!modalRoot.children.length)return;modalRoot.innerHTML='';game?.pause(false);if(modalInvoker?.isConnected)modalInvoker.focus();}
function puzzleTile(m,i,active){const type=i===0?'start':i===8?'goal':m===10?'straight':'elbow';const base={10:1,12:2,6:1,9:3,3:0,2:0,8:0}[m];const angle=((base+state.puzzle.rotations[i])%4)*90;const asset=type+(active.has(i)?'Active':'');return `<button class="rune-tile ${active.has(i)?'lit':''}" data-action="rotate" data-index="${i}" aria-label="${Math.floor(i/3)+1}행 ${i%3+1}열 ${type==='start'?'시작':type==='goal'?'도착':'조각 회전'}" ${i===0||i===8?'disabled':''}>${img('tile')}<img src="${esc(content.assets[asset])}" alt="" style="transform:rotate(${angle}deg)"></button>`;}
function showPuzzle(){const active=reachable(state.puzzle);openModal('끊긴 빛의 길',`<p class="puzzle-note">조각을 눌러 90°씩 돌리세요. 원에서 마름모까지 빛을 이어요.</p><div class="puzzle-grid">${state.puzzle.masks.map((m,i)=>puzzleTile(m,i,active)).join('')}</div><p class="puzzle-note">${connected(state.puzzle)?'빛의 길이 이어졌어요!':'시작과 도착 조각은 고정되어 있어요.'}</p>${state.hint?`<p class="hint-line">${esc(content.hints[state.hint-1])}</p>`:''}<div class="modal-actions">${button('힌트 보기','puzzle-hint','')}${button('온실에 빛 보내기','solve','primary',connected(state.puzzle)?'':'disabled')}</div>`,'puzzle-modal');}
function showReflection(){openModal('오늘 어떤 장면이 남았나요?',`<p>정답은 없어요. 마음에 남은 순간 하나를 골라 주세요.</p><div class="choice-list">${content.reflections.map(r=>button(r.label,'reflect','',`data-id="${r.id}"`)).join('')}</div><p class="private-note">나만의 기록으로 남아요. 부모 리포트에는 포함되지 않아요.</p>`);}
function showMenu(){persist();openModal('잠시 쉬어 가기',`<p>진행은 이 브라우저에 자동으로 기록돼요.</p><div class="choice-list">${button('이야기 계속하기','close')}${button('타이틀로 돌아가기','title','')}${button('새 이야기 시작','new','')}</div><p class="private-note">브라우저 데이터를 지우면 기록도 사라져요.</p>`);}
function action(name,el){switch(name){
 case 'new':if(saved.state){openModal('새 이야기를 시작할까요?',`<p>이 브라우저의 기존 진행과 개인 기록을 새 이야기로 바꿉니다.</p><div class="modal-actions">${button('취소','close','')}${button('새 이야기 시작','confirm-new')}</div>`);}else action('confirm-new');break;
 case 'confirm-new':state=freshState();transition('select');break;
 case 'continue':saved=loadSave();if(saved.state){state=saved.state;render();}else toast(saved.error??'아직 기록된 이야기가 없어요.');break;
 case 'admit':transition('admission');break;case 'arrive':transition('plaza');break;
 case 'next':{const lines=content.dialogue[state.scene];if(state.node<lines.length-1){state.node++;persist();render();}else if(state.scene==='room')showReflection();else transition({plaza:'greenhouse',greenhouse:'adventure',reaction:'choice'}[state.scene]);break;}
 case 'choose':{const choice=content.choices.find(c=>c.id===el.dataset.id);state.choice=choice.id;persist();openModal('시온의 다음 걸음',`<p>${esc(choice.reaction)}</p><div class="modal-actions">${button('My Room으로 돌아가기','go-room')}</div>`);break;}
 case 'go-room':transition('room');break;case 'reflect':state.reflection=el.dataset.id;state.recorded=true;transition('record');break;
 case 'record':transition('record');break;case 'report':transition('report');break;
 case 'title':if(game){game.destroy();game=null;}closeModal();persist();state={...freshState()};render();break;
 case 'menu':showMenu();break;case 'close':closeModal();break;
 case 'return-life':transition('greenhouse');break;case 'interact':game?.interact();break;
 case 'bag':openModal('가방 · 내가 가진 것',state.herbs?`<div class="item-card">${img('herb')}<div><h3>${esc(content.herb.name)} × 1</h3><p>${esc(content.herb.text)}</p></div></div>`:'<p class="empty">아직 보관한 물건이 없어요. 달빛 약초를 찾아보세요.</p>');break;
 case 'journal':openModal('발견 기록 · 내가 아는 것',state.knowledge.length?`<h3 style="margin-top:25px">${esc(content.knowledge.title)}</h3><p>${esc(content.knowledge.text)}</p>`:'<p class="empty">아직 기록한 사실이 없어요. 식물을 살펴보세요.</p>');break;
 case 'hint':openModal('온실의 작은 안내',`<p>${esc(state.restored?content.objectives.restored:state.runeObserved?'룬을 다시 살펴보면 빛의 길을 연결할 수 있어요.':content.objectives.explore)}</p><p>WASD 또는 방향키로 이동하고, 가까이에서 E를 눌러 살펴보세요.</p>`);break;
 case 'puzzle':showPuzzle();break;case 'rotate':{const i=Number(el.dataset.index);rotate(state.puzzle,i);persist();showPuzzle();modalRoot.querySelector(`[data-index="${i}"]`)?.focus();break;}
 case 'puzzle-hint':state.hint=Math.min(3,state.hint+1);persist();showPuzzle();break;
 case 'solve':if(connected(state.puzzle)){recoverWorld(state);refreshAdventure();openModal('온실이 다시 숨을 쉬어요',`<p>룬의 빛이 잎으로 번지고, 시든 유리꽃이 고개를 듭니다.</p><p>입구로 돌아가 시온에게 이야기를 들려주세요.</p><div class="modal-actions">${button('회복된 온실 보기','close')}</div>`);}break;
 case 'question':openModal('시온과 잠깐 이야기',`<p>“${esc(content.question.text)}”</p><div class="choice-list">${content.question.answers.map(a=>button(a,'question-answer','')).join('')}</div><p class="question-label">일반 대화 · 임시 질문</p>`);break;
 case 'question-answer':openModal('시온',`<p>“${esc(content.question.reaction)}”</p>`);break;
 }}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)action(el.dataset.action,el);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(modalRoot.children.length)closeModal();else if(state.scene!=='title')showMenu();}if(e.key==='Tab'&&modalRoot.children.length){const items=[...modalRoot.querySelectorAll('button:not(:disabled)')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
window.addEventListener('blur',()=>{game?.pause(true);persist();});window.addEventListener('focus',()=>game?.pause(!!modalRoot.children.length));window.addEventListener('beforeunload',persist);
try{const response=await fetch('content.json');if(!response.ok)throw new Error('콘텐츠 파일을 읽지 못했어요.');content=await response.json();render();}catch(e){app.innerHTML=`<main class="paper-panel"><h2>이야기를 불러오지 못했어요</h2><p>${esc(e.message)}</p><p>로컬 서버를 실행한 뒤 다시 열어 주세요.</p></main>`;}
